Controllers/CrewRosterReportController.cs
using Crew_Roster.Constants;
using Crew_Roster_EntityAccesslayer;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Crew_Roster.Controllers
{
    public class CrewRosterReportController : Controller
    {
        #region Report

        // GET: CrewRosterReport
        public ActionResult Index()
        {
           // if (String.IsNullOrEmpty(Convert.ToString(Session["Username"])))
             //   return RedirectToAction("login", "User");

            SearchCriteria search = new SearchCriteria();
            search.SearchText = "";
            search.SortColumn = "";
            search.SortOrder = "";
            search.PageIndex = 0;
            search.PageSize = 0;
            //search.UserId = Convert.ToInt16(Session["Userid"]);

            search.FromDate = "";
            search.ToDate = "";
            search.Base = "";
            search.CrewRank = "";

            TempData["name"] = "Cabin Roster Changes - Report";
            TempData["Username"] = Session["Username"];

            ViewBag.CrewType = new SelectList(BusinessHelper.BusinessHelper.Get_CrewRank(search), WebConstants.RepositoryName, WebConstants.RepositoryName);
            ViewBag.StaffID = new SelectList(BusinessHelper.BusinessHelper.Get_employee(search), WebConstants.StaffID, WebConstants.StaffID);
            ViewBag.EmployeeName = new SelectList(BusinessHelper.BusinessHelper.Get_employee(search), WebConstants.StaffID, WebConstants.EmployeeName);
            ViewBag.Rank = new SelectList(BusinessHelper.BusinessHelper.Get_Rank(search), WebConstants.RankID, WebConstants.RepositoryName);
            ViewBag.Base = new SelectList(BusinessHelper.BusinessHelper.Get_Base(search), WebConstants.PresentBaseID, WebConstants.PlaceCode);

            return View();
        }

        public ActionResult ReportView()
        {
            return View();
        }

        // DD
        public JsonResult GetBaseListForDD_rpt(string fromDate, string toDate)
        {
            List<Base> LstBase = new List<Base>();

            SearchCriteria search = new SearchCriteria();
            search.FromDate = fromDate;
            search.ToDate = toDate;

            LstBase = BusinessHelper.BusinessHelper.Get_Base(search);
            var json = from rs in LstBase
                       select new
                       {
                           // AircraftTypeId = rs.AircraftTypeId.ToString() +':'+  rs.AircraftTypeName.ToString()+';',
                           Id = rs.PresentBaseID.ToString(),
                           item = rs.PlaceCode.ToString(),
                           //AircraftTypeName = rs.AircraftTypeName.ToString(),
                           //MonthId = rs.MonthId.ToString(),
                       };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Get_RankListForDD_rpt(string fromDate, string toDate, string baseCode)
        {
            List<Employee> LstRank = new List<Employee>();

            SearchCriteria search = new SearchCriteria();
            search.FromDate = fromDate;
            search.ToDate = toDate;
            search.Base = baseCode == "null" ? "" : baseCode; ;
            LstRank = BusinessHelper.BusinessHelper.Get_Rank(search);
            var json = from rs in LstRank
                       select new
                       {
                           // AircraftTypeId = rs.AircraftTypeId.ToString() +':'+  rs.AircraftTypeName.ToString()+';',
                           Id = rs.RankID.ToString(),
                           item = rs.RepositoryName.ToString(),
                           //AircraftTypeName = rs.AircraftTypeName.ToString(),
                           //MonthId = rs.MonthId.ToString(),
                       };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Get_StaffListForDD_rpt(string fromDate, string toDate, string baseCode, string crewRank)
        {
            List<Employee> LstBase = new List<Employee>();

            SearchCriteria search = new SearchCriteria();
            search.FromDate = fromDate;
            search.ToDate = toDate;
            search.Base = baseCode == "null" ? "" : baseCode;
            search.CrewRank = crewRank == "null" ? "" : crewRank;

            LstBase = BusinessHelper.BusinessHelper.Get_StaffList(search);
            var json = from rs in LstBase
                       select new
                       {
                           // AircraftTypeId = rs.AircraftTypeId.ToString() +':'+  rs.AircraftTypeName.ToString()+';',
                           Id = rs.StaffID.ToString(),
                           item = rs.StaffID.ToString(),
                           //AircraftTypeName = rs.AircraftTypeName.ToString(),
                           //MonthId = rs.MonthId.ToString(),
                       };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Get_EmployeeNameForDD_rpt(string fromDate, string toDate, string baseCode, string crewRank)
        {
            List<Employee> LstEmpList = new List<Employee>();

            SearchCriteria search = new SearchCriteria();
            search.FromDate = fromDate;
            search.ToDate = toDate;
            search.Base = baseCode == "null" ? "" : baseCode;
            search.CrewRank = crewRank == "null" ? "" : crewRank;

            LstEmpList = BusinessHelper.BusinessHelper.Get_employee(search);
            var json = from rs in LstEmpList
                       select new
                       {
                           // AircraftTypeId = rs.AircraftTypeId.ToString() +':'+  rs.AircraftTypeName.ToString()+';',
                           Id = rs.StaffID.ToString(),
                           item = rs.EmployeeName.ToString(),
                           //AircraftTypeName = rs.AircraftTypeName.ToString(),
                           //MonthId = rs.MonthId.ToString(),
                       };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCrewRosterReport(int page, int rows, bool _search, string sortcolumn, string sidx, string sord,string FromDate,string Todate,string Crewtype,string staffId,string empname,string Base,int reportType)
        {
            int recordCount = 0;
            SearchCriteria search = new SearchCriteria();
            search.PageIndex = page;
            search.SearchText = "";
            search.PageSize = rows;
            search.SortColumn = sidx;
            search.SortOrder = sord.ToUpper();
            search.StaffID = staffId == "null" ? "" : staffId;
            search.Rank = Crewtype == "null" ? "" : Crewtype;
            search.Base = Base == "null" ? "" : Base;
            if (empname == "null")
            {
                search.EmployeeName = "";
            }
            else{
                search.EmployeeName = empname;
            }
           
            search.FromDate = FromDate;
            search.ToDate = Todate;
            search.reportType = reportType;

            try
            {
                List<CrewRosterReport> lst = BusinessHelper.BusinessHelper.Get_crewRosterReport(search);
                var lstagent_Togrid = lst.Select(
                       C => new
                       {
                           DutyDate = C.DutyDate,
                           StaffID = C.StaffID,
                           EmployeeName = C.EmployeeName,
                           Rank = C.Rank,
                           EmployeeCategory = C.EmployeeCategory,
                           Base = C.Base,
                           PlannedDuty = C.PlannedDuty,
                           ActualDuty = C.ActualDuty,
                           Changes = C.Changes,
                           NotificationTimeGap = C.NotificationTimeGap,
                           Reportingstarttime = C.Reportingstarttime,
                          // Reportingstarttime = C.Reportingstarttime,
                           ChangedOn = C.ChangedOn,
                           ChangedBy = C.ChangedBy,
                           NotifiedOn = C.NotifiedOn,
                           NotifiedBy = C.NotifiedBy,
                           Remarks = C.Remarks, 
                       }
                    );

                int totalRecords = (lst.Count() > 0) ? recordCount : 0;
                var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);

                var jsonData = new
                {
                    total = totalPages,
                    page,
                    records = totalRecords,
                    rows = lstagent_Togrid
                };
                var res = Json(jsonData, JsonRequestBehavior.AllowGet);
                res.MaxJsonLength = int.MaxValue;

                return res;

                //string json = new JavaScriptSerializer().Serialize(jsonData);
                //return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                //BusinessHelper.BusinessHelper.LogException(ex, "", "Account - ValidateLogin", 2, Convert.ToInt16(Session["Pid"]));
                return Json(new { message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion

        #region Dashboard

        public ActionResult Dashboard(){

         //   if (String.IsNullOrEmpty(Convert.ToString(Session["Username"])))
           //     return RedirectToAction("login", "User");

            SearchCriteria search = new SearchCriteria();
            search.SearchText = "";
            search.SortColumn = "";
            search.SortOrder = "";
            search.PageIndex = 0;
            search.PageSize = 0;
            //search.UserId = Convert.ToInt16(Session["Userid"]);

            search.StaffID = "";
            search.Rank = "";

Controllers/UserController.cs
using Crew_Roster.Constants;
using Crew_Roster_EntityAccesslayer;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;


namespace Crew_Roster.Controllers
{
    public class UserController : Controller
    {

        public ActionResult login()
        {
            return View();
        }

        public ActionResult loginForm()
        {
            return View();
        }


        [HttpPost]
        public JsonResult submitLogin(string username, string password, int ecn)
        {

            // login API Call
            string returnJsonString = "";
            using (HttpClient httpClient = new HttpClient())
            {
                string queryremitter = "https://ent.spicejet.com/ldapauth/api/ldap_api/authenticateAPI";

                ApiParams ApiKeys = new ApiParams()
                {
                    ECN = ecn,
                    password = password,
                    username = username
                };

                // string depositor = "{username: 'ANKR101610845'," + "apikey:'" + 101736595743 + "',mobile:'" + 9881054074 + "'}";

                // Serialize the logon options object.
                string requestBodyAsString = JsonConvert.SerializeObject(ApiKeys);
                // Prepare the request content
                StringContent content =
                    new StringContent(
                        requestBodyAsString,
                        Encoding.UTF8,
                        "application/json"
                    );
                returnJsonString = string.Empty;
                using (var response = httpClient.PostAsync(queryremitter, content).Result)
                {
                    returnJsonString = response.Content.ReadAsStringAsync().Result;
                    var json_res = JsonConvert.DeserializeObject<Responce>(returnJsonString);
                    if (json_res.status == true)
                    {
                        Session["Username"] = json_res.username;
                    }
                }
            }

            return Json(returnJsonString, JsonRequestBehavior.AllowGet);
        }



        public ActionResult Logout()
        {
           // if (String.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
             //   return RedirectToAction("Login", "User");

            Session["Username"] = null;

            return RedirectToAction("Login", "User");

        }
    }
}

Views/User/login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/theme/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    @Styles.Render("~/Content/css")

    <style>
        .bg-gradient-primary {
            background-color: #e62e2d;
            background-image: linear-gradient( 180deg,#e62e2d 10%,#a92828 100%);
            background-size: cover;
        }
        .img-block {
            /*background-image: url('../../Content/theme/img/spicejet-inline.jpg');
            background-repeat: no-repeat;
            background-size: cover;*/
            background: url('../../Content/theme/img/spicejet-inline.jpg') no-repeat center center fixed;
            -webkit-background-size: contain;
            -moz-background-size: contain;
            -o-background-size: contain;
            background-size: contain;
            height: 100vh;
        }
        .btn-primary {
            color: #fff;
            background-color: #e62e2d;
            border-color: #e62e2d;
        }
        #overlay {
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: rgba(0,0,0,0.5);
            z-index: 2;
            cursor: pointer;
        }

        .loadingText {
            margin-right: auto;
            margin-left: auto;
            margin-top: 90px;
            /*margin-bottom: auto;*/
            display: block;
            height: 100px;
            width: 100px;
            color: whitesmoke;
        }

        .login-from {
            padding: 10px;
            text-align: center;
            padding-top: 90px;

        }

        .form-group {
            padding-left: 15px;
            width: 385px;
        }

        .btn {
            margin-left: 15px;
        }

        .row {
            margin-right: 0rem !important;
        }

        .txt-headiing {
            display: block;
            color: red;
            font-weight: bold;
            text-align: center;
            font-size: 25px;
        }
        .txt-subheading {
            display: block;
            color: red;
            font-weight: bold;
            margin-top:-30px;
            text-align: center;
            font-size: 25px;
        }
         .txt-subheading1 {
            display: block;
            color: black;
            font-weight: bold;
            margin-top:-30px;
            text-align: center;
            font-size: 18px;
        }
        .pull-right{
            float:right
        }
        .login-text {
            margin: 40px 0px;
        }
        .login-img{
            
            height:100vh;
            width:100%;

        }
    </style>
</head>

<body>
    <div class="row">
        <div class="col-9">
            <img class="login-img" src="../../Content/theme/img/spicejet-inline.jpg" />
        </div>
        <div class="col-3">
            <div class="login-from">
                <div id="overlay" class="overlay">
                    <span class="loadingText">Loading...</span>
                </div>                
                <img src="~/Content/theme/img/Spicejet-logo-transparent.png" />
                <div class="login-text">
                    <h1 class="txt-headiing">Welcome To </h1>
                    <br />
                    <h3 class="txt-subheading">SpiceJet Reporting</h3>
                    <br />
                    
                </div>
                <h4 class="txt-subheading1">Please login using your Crew Portal Username and Password</h4>
                <br />
                <br />
                <div class="form-group">
                    <label for="username" class="sr-only">Email</label>
                    <input type="text" placeholder="Username" class="form-control" id="username">
                </div>
                @*<div class="form-group">
            <label for="username" class="sr-only">ECN No</label>
            <input type="text" placeholder="ECN No" class="form-control" id="ecn">
        </div>*@
                <div class="form-group">

                    <label for="password" class="sr-only">Password</label>
                    <input type="password" class="form-control" id="password" placeholder="Password">
                </div>
                <br />
                <br />
                <button type="submit" class="btn btn-primary pull-left" id="loginSubmit">Login</button>
            </div>
        </div>
    </div>   
  
        <!-- Bootstrap core JavaScript-->
        <script src="~/Content/theme/vendor/jquery/jquery.min.js"></script>

        <script src="~/Content/theme/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

        <!-- Core plugin JavaScript-->
        <script src="~/Content/theme/vendor/jquery-easing/jquery.easing.min.js"></script>
        <script src="~/Content/theme/js/sb-admin-2.min.js"></script>
        <script src="~/Scripts/pages/login/login.js"></script>
        @Html.Hidden("applicationPath", Url.Content("~"))
</body>

</html>

Views/User/loginForm.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login Form</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/theme/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    @Styles.Render("~/Content/css")

    <style>
        .bg-gradient-primary {
            background-color: #e62e2d;
            background-image: linear-gradient( 180deg,#e62e2d 10%,#a92828 100%);
            background-size: cover;
        }

        .img-block {
            /*background-image: url('../../Content/theme/img/rm_text_logo.jpg');
            background-repeat: no-repeat;
            background-size: cover;*/
            background: url('../../Content/theme/img/spicejet-inline.jpg') no-repeat center center fixed;
            -webkit-background-size: contain;
            -moz-background-size: contain;
            -o-background-size: contain;
            background-size: contain;
            height: 100vh;
        }

        .btn-primary {
            color: #fff;
            background-color: #1f3a71;
            border-color: #1f3a71;
        }

        #overlay {
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: rgba(0,0,0,0.5);
            z-index: 2;
            cursor: pointer;
        }

        .loadingText {
            margin-right: auto;
            margin-left: auto;
            margin-top: 90px;
            /*margin-bottom: auto;*/
            display: block;
            height: 100px;
            width: 100px;
            color: whitesmoke;
        }

        .login-from {
            padding: 10px;
            text-align: center;
            padding-top: 90px;
        }

        .form-group {
            padding-left: 15px;
            width: 385px;
        }

        .btn {
            margin-left: 15px;
        }

        .row {
            margin-right: 0rem !important;
        }

        .txt-headiing {
            display: block;
            color: #1f3a71;
            font-weight: bold;
            text-align: center;
            font-size: 25px;
        }

        .txt-subheading {
            display: block;
            color: #1f3a71;
            font-weight: bold;
            margin-top: -30px;
            text-align: center;
            font-size: 25px;
        }

        .txt-subheading1 {
            display: block;
            color: black;
            font-weight: bold;
            margin-top: -30px;
            text-align: center;
            font-size: 18px;
        }

        .pull-right {
            float: right;
        }

        .login-text {
            margin: 40px 0px;
        }

        .login-img {
            height: 100vh;
            width: 100%;
        }
    </style>
</head>

<body>
    <div class="row">
        <div class="col-9">
            <img class="login-img" src="~/Content/theme/img/spicejet-inline.jpg" />
        </div>
        <div class="col-3">
            <div class="login-from">
                @*<div id="overlay" class="overlay">
                        <span class="loadingText">Loading...</span>
                    </div>*@
                <img src="~/Content/theme/img/Spicejet-logo-transparent.png" />
                <div class="login-text">
                    <h1 class="txt-headiing" style="color:red">Welcome To </h1>
                    <br />
                    <h3 class="txt-subheading" style="color:red">SpiceJet Reporting</h3>
                    <br />
                </div>
                <h4 class="txt-subheading1">Please login using your Crew Portal Username and Password</h4>
                <br />
                <br />
                <div class="form-group">
                    <label for="username" class="sr-only">Email</label>
                    <input type="text" placeholder="Username" class="form-control" id="username">
                </div>
                @*<div class="form-group">
                        <label for="username" class="sr-only">ECN No</label>
                        <input type="text" placeholder="ECN No" class="form-control" id="ecn">
                    </div>*@
                <div class="form-group">

                    <label for="password" class="sr-only">Password</label>
                    <input type="password" class="form-control" id="password" placeholder="Password">
                </div>
                <br />
                <br />
                @*<button type="submit" class="btn btn-primary pull-left" id="loginSubmit">Login</button>*@
                <button style="background-color:red" type="submit" class="btn btn-primary pull-left" onclick="@("window.location.href='" + @Url.Action("Dashboard", "CrewRosterReport") + "'")">Login</button>

            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/theme/vendor/jquery/jquery.min.js"></script>

    <script src="~/Content/theme/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/theme/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/Content/theme/js/sb-admin-2.min.js"></script>

    @Html.Hidden("applicationPath", Url.Content("~"))
</body>

</html>